apiVersion: v1
kind: Secret
metadata:
  name: TAFNAME-certreq-secret-1
  labels:
    serviceName: TAFNAME
    certRequest: "true"
type: Opaque
stringData:
  certReqName: "taftest.xml"
  certReqState: READYSTATE
  certReqMD5: TAFMD5
data:
  certReqData: TAFXML
#  certReqScript: TAFSCRIPT
---
apiVersion: v1
kind: Secret
metadata:
  name: TAFNAME-tls-secret-1
  labels:
    certReqName: "TAFNAME-certreq-secret-1" 
type: Opaque
stringData:
  tlsStoreType: TYPE1
  tlsStoreLocation: LOCATION1
data:
  tlsStoreData: DATA1

---
apiVersion: v1
kind: Secret
metadata:
  name: TAFNAME-tls-secret-2
  labels:
    certReqName: "TAFNAME-certreq-secret-1"
type: Opaque
stringData:
  tlsStoreType: TYPE2
  tlsStoreLocation: LOCATION2
data:
  tlsStoreData: DATA2

