apiVersion: v1
kind: Secret
metadata:
  name: TAFNAME-certreq-secret-1
  labels:
    serviceName: TAFNAME
    certRequest: "true"
type: Opaque
stringData:
  certReqName: "taftest.xml"
data:
  certReqData: TAFXML
#  certReqScript: TAFSCRIPT
#  certReqState: {{ .Values.service.emptyState }}
---
apiVersion: v1
kind: Secret
metadata:
  name: TAFNAME-tls-secret-1
  labels:
    certReqName: "TAFNAME-certreq-secret-1" 
type: Opaque
#stringData:
#  tlsStoreLocation: {{ .Values.service.noneState }}
#  tlsStoreType: {{ .Values.service.noneState }}
#data:
#  tlsStoreData: {{ .Values.service.emptyData }}
---
apiVersion: v1
kind: Secret
metadata:
  name: TAFNAME-tls-secret-2
  labels:
    certReqName: "TAFNAME-certreq-secret-1"
type: Opaque
#stringData:
#  tlsStoreLocation: {{ .Values.service.noneState }}
#  tlsStoreType: {{ .Values.service.noneState }}
#data:
#  tlsStoreData: {{ .Values.service.emptyData }}

